version: 2.1
orbs:
  node: circleci/node@5.0.3
workflows:
  compile-workflow:
    jobs:
      - build:
          context:
            - DOCKER_CONTEXT
jobs:
  build:
    docker:
      - image: rocker/r-base:4.2.2
    steps:
      - checkout
      - run:
          name: Install package dependencies
          command: R -e "install.packages('devtools');install.packages('roxygen2')"
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check *tar.gz